import { DS } from "../design/tokens";
import { DeFybLogo } from "../components/svg";

const Section = ({ title, children }) => (
  <div style={{ marginBottom: "40px" }}>
    <h2 style={{
      fontFamily: DS.fonts.display, fontSize: "18px", color: DS.colors.text,
      marginBottom: "12px", paddingBottom: "8px",
      borderBottom: `1px solid ${DS.colors.border}`,
    }}>
      {title}
    </h2>
    {children}
  </div>
);

const P = ({ children }) => (
  <p style={{ fontSize: "14px", color: DS.colors.textMuted, lineHeight: 1.7, marginBottom: "10px" }}>
    {children}
  </p>
);

const Li = ({ children }) => (
  <li style={{ fontSize: "14px", color: DS.colors.textMuted, lineHeight: 1.7, marginBottom: "6px" }}>
    {children}
  </li>
);

const navigateTo = (path, view) => {
  if (typeof window !== "undefined") {
    window.history.pushState({ defyb: true, view }, "", path);
    window.dispatchEvent(new PopStateEvent("popstate", { state: { defyb: true, view } }));
  }
};

export const TermsOfService = ({ onBack }) => (
  <div style={{
    minHeight: "100vh", background: DS.colors.bg, color: DS.colors.text,
    fontFamily: DS.fonts.body,
  }}>
    <div style={{ maxWidth: "740px", margin: "0 auto", padding: "48px 24px 80px" }}>

      <div style={{ marginBottom: "40px" }}>
        <DeFybLogo size={28} />
        <h1 style={{
          fontFamily: DS.fonts.display, fontSize: "30px", color: DS.colors.text,
          marginTop: "20px", marginBottom: "4px",
        }}>
          Terms of Service
        </h1>
        <p style={{ fontSize: "13px", color: DS.colors.textDim }}>
          Effective Date: March 15, 2026 &middot; DeFyb LLC
        </p>
      </div>

      <Section title="1. Acceptance of Terms">
        <P>
          By accessing or using the DeFyb platform at defyb.org (the "Service"), you agree to be
          bound by these Terms of Service ("Terms"). If you are using the Service on behalf of a
          healthcare practice or organization, you represent that you have authority to bind that
          entity to these Terms. If you do not agree, do not use the Service.
        </P>
      </Section>

      <Section title="2. Description of Service">
        <P>
          DeFyb provides coding intelligence, revenue capture analysis, and workflow tools for
          healthcare practices. The Service analyzes encounter documentation to suggest E/M coding
          levels, identify documentation gaps, and estimate revenue impact.
        </P>
        <P>
          <strong>DeFyb is a decision-support tool, not an autonomous coder.</strong> All coding
          recommendations are suggestions only. The treating clinician or authorized billing
          professional retains full responsibility for the final code selection, claim submission,
          and clinical documentation. DeFyb does not make coding decisions on behalf of any
          practice or provider.
        </P>
      </Section>

      <Section title="3. Accounts and Access">
        <P>
          To use the Service, your practice must have an account provisioned by DeFyb. You are
          responsible for maintaining the confidentiality of your login credentials and for all
          activity that occurs under your account.
        </P>
        <P>
          You agree to provide accurate and complete information during account setup and to notify
          us promptly of any unauthorized access to your account.
        </P>
      </Section>

      <Section title="4. Clinical Responsibility and Disclaimer">
        <P>
          <strong>THE SERVICE IS NOT A SUBSTITUTE FOR PROFESSIONAL MEDICAL JUDGMENT, CERTIFIED
          CODING EXPERTISE, OR LEGAL ADVICE.</strong>
        </P>
        <ul style={{ paddingLeft: "20px", margin: "0 0 12px" }}>
          <Li>Coding recommendations are generated by rule-based analysis and are intended as
            decision support, not definitive coding assignments.</Li>
          <Li>The clinician or certified coder must independently verify that the selected code
            accurately reflects the encounter documentation and meets all payer requirements.</Li>
          <Li>DeFyb does not guarantee the accuracy, completeness, or compliance of any
            recommendation with any specific payer, CMS, or regulatory standard.</Li>
          <Li>Revenue impact estimates are illustrative projections based on available rate data
            and do not constitute a guarantee of reimbursement.</Li>
        </ul>
        <P>
          By using the Service, you acknowledge that clinical and coding decisions remain solely
          with the practice and its authorized personnel.
        </P>
      </Section>

      <Section title="5. Acceptable Use">
        <P>You agree not to:</P>
        <ul style={{ paddingLeft: "20px", margin: "0 0 12px" }}>
          <Li>Use the Service to submit knowingly false or fraudulent documentation</Li>
          <Li>Attempt to circumvent access controls, authentication, or security measures</Li>
          <Li>Use the Service to systematically upcode encounters without supporting documentation</Li>
          <Li>Share login credentials with unauthorized individuals</Li>
          <Li>Use automated tools, bots, or scripts to access the Service without prior written consent</Li>
          <Li>Reverse-engineer, decompile, or attempt to extract the source code of the Service</Li>
        </ul>
        <P>We reserve the right to suspend or terminate accounts that violate these terms.</P>
      </Section>

      <Section title="6. Data and Privacy">
        <P>
          Your use of the Service is also governed by our{" "}
          <span
            onClick={() => navigateTo("/privacy", "privacy")}
            style={{ color: DS.colors.shock, cursor: "pointer", textDecoration: "underline" }}
          >
            Privacy Policy
          </span>, which describes how we collect, use, and protect your information,
          including protected health information (PHI).
        </P>
        <P>
          You retain ownership of all encounter data and clinical documentation submitted to the
          Service. DeFyb retains a limited license to process this data solely for the purpose of
          providing the Service, as described in the Privacy Policy and any applicable Business
          Associate Agreement.
        </P>
      </Section>

      <Section title="7. HIPAA and Business Associate Agreement">
        <P>
          If your use of the Service involves the transmission or processing of PHI, a Business
          Associate Agreement (BAA) between DeFyb LLC and your practice may be required. DeFyb
          offers BAAs for all qualifying engagements.
        </P>
        <P>
          You are responsible for determining whether a BAA is required for your use of the
          Service and for contacting us to execute one before submitting PHI. Contact{" "}
          <a href="mailto:torey@defyb.org" style={{ color: DS.colors.shock, textDecoration: "none" }}>
            torey@defyb.org
          </a>{" "}to request a BAA.
        </P>
      </Section>

      <Section title="8. Subscription and Billing">
        <P>
          Paid features of the Service are offered on a subscription basis. Subscription details,
          including pricing tiers, provider counts, and optional add-ons, are presented during
          checkout.
        </P>
        <ul style={{ paddingLeft: "20px", margin: "0 0 12px" }}>
          <Li>Subscriptions are billed monthly through Stripe unless otherwise agreed in writing.</Li>
          <Li>You may manage your subscription, update payment methods, and view invoices through
            the Stripe customer portal accessible from within the Service.</Li>
          <Li>If payment fails, we may suspend access to paid features after a reasonable
            grace period and notification.</Li>
          <Li>One-time implementation fees, where applicable, are non-refundable.</Li>
        </ul>
        <P>
          We reserve the right to modify pricing with 30 days' advance notice to affected accounts.
          Continued use after a pricing change constitutes acceptance of the new pricing.
        </P>
      </Section>

      <Section title="9. Intellectual Property">
        <P>
          The Service, including its design, code, algorithms, documentation, and branding, is the
          property of DeFyb LLC and is protected by applicable intellectual property laws. These
          Terms do not grant you any ownership rights in the Service.
        </P>
        <P>
          You retain all rights to your practice data and clinical documentation. We claim no
          ownership of data you submit to the Service.
        </P>
      </Section>

      <Section title="10. Limitation of Liability">
        <P>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, DEFYB LLC SHALL NOT BE LIABLE FOR ANY INDIRECT,
          INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM OR RELATED TO YOUR
          USE OF THE SERVICE, INCLUDING BUT NOT LIMITED TO:
        </P>
        <ul style={{ paddingLeft: "20px", margin: "0 0 12px" }}>
          <Li>Incorrect coding recommendations or revenue estimates</Li>
          <Li>Claim denials, payer audits, or regulatory actions resulting from coding decisions</Li>
          <Li>Loss of revenue, data, or business opportunities</Li>
          <Li>Service interruptions, delays, or errors</Li>
        </ul>
        <P>
          OUR TOTAL LIABILITY FOR ANY CLAIM ARISING FROM THESE TERMS OR YOUR USE OF THE SERVICE
          SHALL NOT EXCEED THE FEES PAID BY YOU TO DEFYB IN THE TWELVE (12) MONTHS PRECEDING
          THE CLAIM.
        </P>
      </Section>

      <Section title="11. Indemnification">
        <P>
          You agree to indemnify and hold harmless DeFyb LLC, its officers, employees, and agents
          from any claims, damages, losses, or expenses (including reasonable attorneys' fees)
          arising from:
        </P>
        <ul style={{ paddingLeft: "20px", margin: "0 0 12px" }}>
          <Li>Your use of the Service</Li>
          <Li>Your coding or billing decisions</Li>
          <Li>Your violation of these Terms</Li>
          <Li>Your violation of any applicable law or regulation</Li>
        </ul>
      </Section>

      <Section title="12. Warranty Disclaimer">
        <P>
          THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND,
          WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF
          MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
        </P>
        <P>
          We do not warrant that the Service will be uninterrupted, error-free, or that coding
          recommendations will be accurate or compliant with any specific standard. Clinical and
          coding judgment remains the sole responsibility of the practice.
        </P>
      </Section>

      <Section title="13. Termination">
        <P>
          Either party may terminate the Service relationship at any time. You may cancel your
          subscription through the billing portal or by contacting us. We may terminate or suspend
          your access for violation of these Terms with notice.
        </P>
        <P>
          Upon termination, you may request export of your data within 30 days. After 30 days, we
          may delete your data in accordance with our retention policy, except where retention is
          required by law.
        </P>
      </Section>

      <Section title="14. Governing Law">
        <P>
          These Terms are governed by and construed in accordance with the laws of the State of
          Minnesota, without regard to conflict-of-law principles. Any disputes arising from these
          Terms or the Service shall be resolved in the state or federal courts located in
          Minnesota.
        </P>
      </Section>

      <Section title="15. Changes to These Terms">
        <P>
          We may update these Terms from time to time. We will notify registered users of material
          changes via email or in-app notification at least 30 days before changes take effect.
          Continued use of the Service after the effective date constitutes acceptance of the
          revised Terms.
        </P>
      </Section>

      <Section title="16. Contact">
        <P>
          DeFyb LLC<br />
          Email:{" "}
          <a href="mailto:torey@defyb.org" style={{ color: DS.colors.shock, textDecoration: "none" }}>
            torey@defyb.org
          </a>
        </P>
      </Section>

      {/* Footer nav */}
      <div style={{
        display: "flex", justifyContent: "center", gap: "24px",
        paddingTop: "32px", borderTop: `1px solid ${DS.colors.border}`,
        fontSize: "13px",
      }}>
        <span onClick={onBack} style={{ color: DS.colors.textMuted, cursor: "pointer" }}>
          &larr; Back to site
        </span>
        <span
          onClick={() => navigateTo("/privacy", "privacy")}
          style={{ color: DS.colors.shock, cursor: "pointer" }}
        >
          Privacy Policy
        </span>
        <span
          onClick={() => navigateTo("/security", "security")}
          style={{ color: DS.colors.shock, cursor: "pointer" }}
        >
          Security
        </span>
      </div>
    </div>
  </div>
);
