import fs from "fs";

const reportPath = process.argv[2] || "autopilot-report.md";
const appPath = "src/App.jsx";
const backlogPath = "AUTOPILOT_BACKLOG.md";

const report = fs.existsSync(reportPath) ? fs.readFileSync(reportPath, "utf8") : "";
let app = fs.readFileSync(appPath, "utf8");

const applied = [];
const skipped = [];

const routeIntentSnippet = `\n  const getRouteIntent = () => {\n    if (typeof window === "undefined") return null;\n    const path = (window.location.pathname || "").toLowerCase();\n    if (path === "/team") return "team";\n    if (path === "/tool" || path === "/app") return "tool";\n    if (window.location.search.includes("team")) return "team";\n    if (window.location.search.includes("tool")) return "tool";\n    return null;\n  };\n`;

if (!app.includes("const getRouteIntent =")) {
  const anchor = "  const isTeamUser = (user) => {";
  const idx = app.indexOf(anchor);
  if (idx !== -1) {
    const endIdx = app.indexOf("  // Check for existing session on mount", idx);
    if (endIdx !== -1) {
      app = `${app.slice(0, endIdx)}${routeIntentSnippet}\n${app.slice(endIdx)}`;
      applied.push("Added explicit route-intent handler for /team and /tool.");
    } else {
      skipped.push("Could not locate insertion point for route-intent helper.");
    }
  } else {
    skipped.push("Could not find team-user block for route-intent helper.");
  }
}

const hasCopyButtons = app.includes("Copy Billing Summary") && app.includes("Copy Note Additions");
const hasHistory = app.includes("Recent Analyses (last 20)");
const hasGuardrail = app.includes("Manual review required");

if (!hasCopyButtons) skipped.push("Copy action buttons missing; skipped auto-patch (manual review required).");
if (!hasHistory) skipped.push("History panel missing; skipped auto-patch (manual review required).");
if (!hasGuardrail) skipped.push("Low-confidence guardrail missing; skipped auto-patch (manual review required).");

if (applied.length > 0) {
  fs.writeFileSync(appPath, app, "utf8");
}

const recLines = report
  .split("\n")
  .filter((l) => l.startsWith("- P1:") || l.startsWith("- P2:"));

const backlogLines = [
  "# Autopilot Backlog",
  "",
  "This file is generated by `scripts/autopilot-autofix.mjs`.",
  "",
  "## Extracted Priorities",
  ...(recLines.length > 0 ? recLines : ["- None detected from latest report."]),
  "",
  "## Autofix Status",
  ...(applied.length > 0 ? applied.map((a) => `- [APPLIED] ${a}`) : ["- [APPLIED] No deterministic low-risk patch applied this run."]),
  ...(skipped.length > 0 ? skipped.map((s) => `- [SKIPPED] ${s}`) : []),
  "",
];

fs.writeFileSync(backlogPath, `${backlogLines.join("\n")}\n`, "utf8");

console.log(`Applied fixes: ${applied.length}`);
console.log(`Skipped fixes: ${skipped.length}`);
